baseURL = "https://cclb.ch/"
languageCode = "fr"
title = "Chœur de Colombier-La BARC"

disableKinds = ["404", "robotstxt", "rss", "section", "taxonomy", "term" ]
noBuildLock = true

[menus]
[[menus.main]]
name = "Accès membres"
url = "https://www.dropbox.com/scl/fo/sefnhp1c7fijl4frd8snp/AK7UV_BOFCdsZbJeO80gwu0?rlkey=p9syh73jk3ezdnnujh120yuki&st=uqv6kztr&dl=0"
weight = 100

[markup.goldmark.parser.attribute]
block = true

[minify]
minifyOutput = true
[minify.tdewolff.html]
keepDefaultAttrVals = false
keepQuotes = true
keepWhitespace = true
